name: ads-b
version: git
summary: ADS-B, Mode S, and Mode 3A/3C demodulator and decoder
description: |
  This snap provides the dump1090 ADS-B, Mode S, and Mode 3A/3C demodulator and
  decoder to receive and decode aircraft transponder messages received
  via an SDR (software defined radio) USB dongle.

  It uses the [dump1090-fa](https://github.com/flightaware/dump1090) fork.

  It also includes a [web-based
  interface](https://github.com/wiedehopf/tar1090) to display received
  aircrafts information and positions on map.

  The snap has a few configuration options:

   * `coord.lat`, `coord.lon`: GPS coordinates of the receiver
   * `web.port`: TCP port for the web interface (default: 8080)

license: GPL-2.0+
confinement: strict
grade: stable
base: core20
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  dump1090:
    command: bin/dump1090.wrapper
    daemon: simple
    install-mode: disable
    plugs:
      - network-bind
      - network-observe
      - raw-usb

  view:
    command: bin/view1090
    plugs:
      - home
      - network

  lighttpd:
    command: bin/lighttpd.wrapper
    daemon: simple
    install-mode: disable
    plugs:
      - network-bind

parts:
  dump1090:
    plugin: nil
    source: https://github.com/flightaware/dump1090
    source-type: git
    build-packages:
      - build-essential
      - libbladerf-dev
      - libhackrf-dev
      - liblimesuite-dev
      - libncurses5-dev
      - librtlsdr-dev
      - libusb-1.0-0-dev
      - pkg-config
    stage-packages:
      - libbladerf2
      - libhackrf0
      - liblimesuite20.01-1
      - librtlsdr0
      - libusb-1.0-0
    override-build: |
      make -j"$SNAPCRAFT_PARALLEL_BUILD_COUNT"
      BIN="$SNAPCRAFT_PART_INSTALL/bin/"
      mkdir -p "$BIN"
      cp -a dump1090 view1090 "$BIN"
    prime:
      - bin/
      - lib/*linux-gnu/
      - usr/lib/*linux-gnu/

  tar1090:
    plugin: nil
    source: https://github.com/wiedehopf/tar1090
    source-type: git
    override-build: |
      cp -a html "$SNAPCRAFT_PART_INSTALL"

  lighttpd:
    plugin: autotools
    source: https://git.lighttpd.net/lighttpd/lighttpd1.4.git
    source-type: git
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - libpcre2-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - zlib1g
    override-build: |
      snapcraftctl build
      CONFDIR="$SNAPCRAFT_PART_INSTALL/etc/lighttpd"
      mkdir -p "$CONFDIR"
      cp "$SNAPCRAFT_PART_SRC/doc/config/conf.d/mime.conf" "$CONFDIR"
    organize:
      usr/sbin/lighttpd: bin/lighttpd
      usr/lib/mod_*: usr/lib/lighttpd/
    stage:
      - etc/
      - usr/lib/
      - bin/

  tree:
    plugin: dump
    source: tree
