name: ads-b
version: git
summary: ADS-B, Mode S, and Mode 3A/3C demodulator and decoder
description: |
  This snap provides the dump1090 ADS-B, Mode S, and Mode 3A/3C demodulator and
  decoder to receive and decode aircraft transponder messages received
  via an SDR (software defined radio) USB dongle.

  See https://github.com/albertodonato/ads-b-snap for more details and
  configuration options.
confinement: strict
grade: stable
base: core22
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

layout:
  /etc/fr24feed.ini:
    bind-file: $SNAP/etc/fr24feed.ini

apps:
  dump1090:
    command: bin/dump1090.wrapper
    daemon: simple
    install-mode: disable
    plugs:
      - network-bind
      - network-observe
      - raw-usb

  view:
    command: bin/view1090
    plugs:
      - home
      - network

  lighttpd:
    command: bin/lighttpd.wrapper
    daemon: simple
    install-mode: disable
    plugs:
      - network-bind

  fr24feed:
    command: bin/fr24feed.wrapper
    daemon: simple
    install-mode: disable
    plugs:
      - network-bind

parts:
  dump1090:
    plugin: nil
    source: https://github.com/flightaware/dump1090
    source-type: git
    build-packages:
      - build-essential
      - libbladerf-dev
      - libhackrf-dev
      - liblimesuite-dev
      - libncurses5-dev
      - librtlsdr-dev
      - libusb-1.0-0-dev
      - pkg-config
    stage-packages:
      - libbladerf2
      - libhackrf0
      - liblimesuite20.10-1
      - librtlsdr0
      - libusb-1.0-0
    override-build: |
      make -j"$CRAFT_PARALLEL_BUILD_COUNT"
      BIN="$CRAFT_PART_INSTALL/bin/"
      mkdir -p "$BIN"
      cp -a dump1090 view1090 "$BIN"
    prime:
      - bin/
      - lib/*linux-gnu/
      - usr/lib/*linux-gnu/

  tar1090:
    plugin: nil
    source: https://github.com/wiedehopf/tar1090
    source-type: git
    override-build: |
      cp -a html "$CRAFT_PART_INSTALL"

  lighttpd:
    plugin: autotools
    source: https://git.lighttpd.net/lighttpd/lighttpd1.4.git
    source-type: git
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - libpcre2-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - zlib1g
    override-build: |
      craftctl default
      CONFDIR="$CRAFT_PART_INSTALL/etc/lighttpd"
      mkdir -p "$CONFDIR"
      cp "$CRAFT_PART_SRC/doc/config/conf.d/mime.conf" "$CONFDIR"
    organize:
      usr/sbin/lighttpd: bin/lighttpd
      usr/lib/mod_*: usr/lib/lighttpd/
    stage:
      - etc/
      - usr/lib/
      - bin/

  fr24feed:
    plugin: make
    source: fr24feed
    build-packages:
      - curl

  tree:
    plugin: dump
    source: tree
